spindle:
  name: Spindle
  port: COM15
  velocity: 10000
  home_search_velocity: 10000
  home_timeout: 30
  home_centering_time: 0.4
  notch_increments: 1000

staker:
  name: Staker
  port: COM14
  velocity: 30000
  home_search_velocity: 30000
  home_timeout: 30
  home_centering_time: 0

clamp:
  name: Clamp
  port: COM13
  velocity: 60000
  home_search_velocity: 60000
  home_timeout: 30
  home_centering_time: 0.2

feeder:
  name: Feeder
  port: COM3
  velocity: 30
  home_search_velocity: 30
  home_timeout: 30
  home_centering_time: 0.6
  tip_timeout: 15